/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import java.sql.*;
import java.util.regex.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Dikshita Aggarwal
 */
public class register extends javax.swing.JFrame {

    /**
     * Creates new form register
     */
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        age = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        comments = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nameErr = new javax.swing.JLabel();
        ageErr = new javax.swing.JLabel();
        cityErr = new javax.swing.JLabel();
        bgErr = new javax.swing.JLabel();
        bg = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel2.setText("Register Donor");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel3.setText("Name :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel4.setText("Age :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));

        jLabel5.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel5.setText("City :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel6.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel6.setText("Blood Group: ");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jLabel7.setFont(new java.awt.Font("Bodoni MT", 1, 14)); // NOI18N
        jLabel7.setText("Medical History :");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, -1));

        name.setBackground(new java.awt.Color(255, 237, 237));
        name.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        name.setForeground(new java.awt.Color(254, 112, 112));
        name.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                nameFocusLost(evt);
            }
        });
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        jPanel2.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 145, -1));

        age.setBackground(new java.awt.Color(255, 237, 237));
        age.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        age.setForeground(new java.awt.Color(254, 112, 112));
        age.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                ageFocusLost(evt);
            }
        });
        age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageActionPerformed(evt);
            }
        });
        jPanel2.add(age, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 145, -1));

        city.setBackground(new java.awt.Color(255, 237, 237));
        city.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        city.setForeground(new java.awt.Color(254, 112, 112));
        city.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                cityFocusLost(evt);
            }
        });
        jPanel2.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 145, -1));

        comments.setBackground(new java.awt.Color(255, 237, 237));
        comments.setColumns(20);
        comments.setFont(new java.awt.Font("Cascadia Mono", 0, 12)); // NOI18N
        comments.setForeground(new java.awt.Color(254, 112, 112));
        comments.setLineWrap(true);
        comments.setRows(5);
        comments.setText("Any medical illness of concern\n");
        comments.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                commentsFocusGained(evt);
            }
        });
        jScrollPane1.setViewportView(comments);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 207, 76));

        jButton1.setBackground(new java.awt.Color(255, 204, 204));
        jButton1.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(249, 94, 94));
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 204, 204));
        jButton2.setFont(new java.awt.Font("Copperplate Gothic Light", 1, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(249, 94, 94));
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 350, -1, -1));

        nameErr.setForeground(new java.awt.Color(255, 0, 51));
        nameErr.setText("*Required");
        jPanel2.add(nameErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 145, -1));

        ageErr.setForeground(new java.awt.Color(255, 0, 51));
        ageErr.setText("*Required");
        jPanel2.add(ageErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 145, -1));

        cityErr.setForeground(new java.awt.Color(255, 0, 51));
        cityErr.setText("*Required");
        jPanel2.add(cityErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 145, -1));

        bgErr.setForeground(new java.awt.Color(255, 0, 51));
        bgErr.setText("*Required");
        jPanel2.add(bgErr, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 145, -1));

        bg.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A+", "A-", "B+", "B-", "AB+", "AB-", "O+", "O-" }));
        jPanel2.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 140, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(29, 47, 370, 400));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Algerian", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Blood Donation Camp");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageActionPerformed

    private void nameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFocusLost
        // TODO add your handling code here:
String regx = "^[\\p{L} .'-]+$";
Pattern p = Pattern.compile(regx);        
if(name.getText().isEmpty()){
            name.requestFocus();
}
else if(!p.matcher(name.getText()).matches()){
    nameErr.setText("*Only characters and spaces allowed!");
    name.requestFocus();
}
else{
 nameErr.setVisible(false);
}
    }//GEN-LAST:event_nameFocusLost

    private void ageFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_ageFocusLost
    if(age.getText().isEmpty()){
               age.requestFocus();
}
   else {
        try{
            int a=Integer.parseInt(age.getText());
            if(a<18 || a>100){
                ageErr.setText("*Not elligible");
                age.requestFocus();
            }
            else{
                ageErr.setVisible(false);
            }
        }
        catch(NumberFormatException e){
            ageErr.setText("*Invalid input");
            age.requestFocus();
            }
        }
    }//GEN-LAST:event_ageFocusLost

    private void cityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFocusLost
        if(city.getText().isEmpty()){
              city.requestFocus();
    }
    String regx = "^[\\p{L} .'-]+$";
    Pattern p = Pattern.compile(regx);
    if(!p.matcher(city.getText()).matches()){
         cityErr.setText("*Invalid Input");
         city.requestFocus();
    }
    else
        cityErr.setVisible(false);
    }//GEN-LAST:event_cityFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        name.setText("");
        age.setText("");
        city.setText("");
        bg.setSelectedIndex(0);
        comments.setText("Any medical illness of concern");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
          String d_name=name.getText();
          int d_age=Integer.parseInt(age.getText());
          String d_city=city.getText();
          String d_bg=(String)bg.getSelectedItem();
          String comm=comments.getText();
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/users","root","password");
         String sql = "Insert into donors(name,age,city,bloodgroup,medicalhistory) VALUES (?,?,?,?,?)";
         PreparedStatement pst = con.prepareStatement(sql);
         pst.setString(1,d_name);
         pst.setInt(2,d_age);
         pst.setString(3,d_city);
         pst.setString(4,d_bg);
         pst.setString(5,comm);
         int i=pst.executeUpdate();
         if(i>0){
            JOptionPane.showMessageDialog(null,"Successfully inserted!");
             HomePage hp=new HomePage(d_name);
             hp.setVisible(true);
             setVisible(false);
        }   
    }catch(Exception e){
       JOptionPane.showMessageDialog(null,e);
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void commentsFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_commentsFocusGained
        // TODO add your handling code here:
        comments.setText("");
    }//GEN-LAST:event_commentsFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField age;
    private javax.swing.JLabel ageErr;
    private javax.swing.JComboBox<String> bg;
    private javax.swing.JLabel bgErr;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityErr;
    private javax.swing.JTextArea comments;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameErr;
    // End of variables declaration//GEN-END:variables
}
